package core

import "testing"

func diffOpsEqual(t *testing.T, got []DiffLine, want []DiffLine) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("got %d diff lines, want %d\ngot:  %+v\nwant: %+v", len(got), len(want), got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("line %d: got %+v, want %+v", i, got[i], want[i])
		}
	}
}

func TestDiffText_IdenticalInput(t *testing.T) {
	lines, err := DiffText("a\nb\nc", "a\nb\nc")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	for _, l := range lines {
		if l.Op != DiffEqual {
			t.Errorf("identical input produced a non-equal line: %+v", l)
		}
	}
	if len(lines) != 3 {
		t.Errorf("got %d lines, want 3", len(lines))
	}
}

func TestDiffText_SingleLineChange(t *testing.T) {
	lines, err := DiffText("line1\nline2\nline3", "line1\nlineX\nline3")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []DiffLine{
		{DiffEqual, "line1"},
		{DiffDel, "line2"},
		{DiffAdd, "lineX"},
		{DiffEqual, "line3"},
	}
	diffOpsEqual(t, lines, want)
}

func TestDiffText_DeletedLine(t *testing.T) {
	lines, err := DiffText("apple\nbanana\ncherry", "apple\ncherry")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []DiffLine{
		{DiffEqual, "apple"},
		{DiffDel, "banana"},
		{DiffEqual, "cherry"},
	}
	diffOpsEqual(t, lines, want)
}

func TestDiffText_EmptyAToNonEmptyB(t *testing.T) {
	lines, err := DiffText("", "new line")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []DiffLine{{DiffAdd, "new line"}}
	diffOpsEqual(t, lines, want)
}

func TestDiffText_NonEmptyAToEmptyB(t *testing.T) {
	lines, err := DiffText("old line", "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := []DiffLine{{DiffDel, "old line"}}
	diffOpsEqual(t, lines, want)
}

func TestDiffText_BothEmpty(t *testing.T) {
	lines, err := DiffText("", "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(lines) != 0 {
		t.Errorf("got %d lines for two empty inputs, want 0", len(lines))
	}
}

func TestDiffText_CRLFNormalizedToLF(t *testing.T) {
	// splitLines normalizes \r\n to \n before splitting, so a file
	// generated by different software (Windows line endings) doesn't
	// spuriously diff against the same content with Unix line endings.
	lines, err := DiffText("a\r\nb\r\nc", "a\nb\nc")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	for _, l := range lines {
		if l.Op != DiffEqual {
			t.Errorf("CRLF vs LF of the same content should diff as identical, got: %+v", l)
		}
	}
}

func TestDiffText_TooLargeInputIsRejected(t *testing.T) {
	// maxDiffCells = 4_000_000. Building two inputs whose line-count
	// product exceeds that without actually allocating megabytes of
	// text: 2001 * 2001 > 4,000,000, and each "line" is a single
	// distinct character so building the strings stays cheap.
	big := make([]byte, 0, 2001*2)
	for i := 0; i < 2001; i++ {
		if i > 0 {
			big = append(big, '\n')
		}
		big = append(big, byte('a'+i%26))
	}
	_, err := DiffText(string(big), string(big))
	if err == nil {
		t.Fatal("expected an error for input exceeding the diff size cap, got nil")
	}
	if CodeOf(err) != CodeInput {
		t.Errorf("CodeOf(err) = %d, want CodeInput (%d)", CodeOf(err), CodeInput)
	}
}

func TestFormatDiff_Prefixes(t *testing.T) {
	lines := []DiffLine{
		{DiffEqual, "same"},
		{DiffDel, "removed"},
		{DiffAdd, "added"},
	}
	got := FormatDiff(lines)
	want := "  same\n- removed\n+ added\n"
	if got != want {
		t.Errorf("FormatDiff = %q, want %q", got, want)
	}
}

func TestFormatDiff_Empty(t *testing.T) {
	got := FormatDiff(nil)
	if got != "" {
		t.Errorf("FormatDiff(nil) = %q, want empty string", got)
	}
}
